### ISSUE TITLE
Types broken in 4.1.0

### ISSUE THREAD

**Issue by coojames1010** [pixijs/sound#182] opened 2021-12-31 16:59 UTC
```
Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:1882:5 - error TS2416: Property 'init' in type 'WebAudioInstance' is not assignable to the same property in base type 'IMediaInstance'.
  Type '(media: WebAudioMedia) => void' is not assignable to type '(parent: IMedia) => void'.
    Types of parameters 'media' and 'parent' are incompatible.
      Type 'IMedia' is missing the following properties from type 'WebAudioMedia': parent, source, _nodes, _source, and 4 more.

1882     init(media: WebAudioMedia): void;
         ~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:1920:5 - error TS2416: Property 'create' in type 'WebAudioMedia' is not assignable to the same property in base type 'IMedia'.
  Type '() => WebAudioInstance' is not assignable to type '() => IMediaInstance'.
    Type 'WebAudioInstance' is missing the following properties from type 'IMediaInstance': once, on, off

1920     create(): WebAudioInstance;
         ~~~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:385:5 - error TS2416: Property 'init' in type 'HTMLAudioInstance' is not assignable to the same property in base type 'IMediaInstance'.
  Type '(media: HTMLAudioMedia) => void' is not assignable to type '(parent: IMedia) => void'.
    Types of parameters 'media' and 'parent' are incompatible.
      Type 'IMedia' is missing the following properties from type 'HTMLAudioMedia': parent, _source, source

385     init(media: HTMLAudioMedia): void;
        ~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:450:5 - error TS2416: Property 'create' in type 'HTMLAudioMedia' is not assignable to the same property in base type 'IMedia'.
  Type '() => HTMLAudioInstance' is not assignable to type '() => IMediaInstance'.
    Type 'HTMLAudioInstance' is missing the following properties from type 'IMediaInstance': once, on, off

450     create(): HTMLAudioInstance;
```

**Comment by bigtimebuddy** [comment] 2021-12-31 19:56
I cannot reproduce, can you please provide your version of TypeScript, your tsconfig.json and/or a simple project that reproduces this error?

**Comment by bigtimebuddy** [comment] 2021-12-31 20:06
Could you try this [sound.d.ts](https://gist.githubusercontent.com/bigtimebuddy/83e72a508fc01985a254dbd46d3ce42c/raw/85d0c3b34002614f3c3c672be3081c7b07f8e2ed/pixi-sound.d.ts) instead and see if it makes any difference?

**Comment by coojames1010** [comment] 2021-12-31 20:22
With that new sound.d.ts I get the following now:

Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:1734:15 - error TS2420: Class 'WebAudioInstance' incorrectly implements interface 'IMediaInstance<WebAudioMedia>'.
  Type 'WebAudioInstance' is missing the following properties from type 'IMediaInstance<WebAudioMedia>': once, on, off

1734 declare class WebAudioInstance extends EventEmitter implements IMediaInstance<WebAudioMedia> {
                   ~~~~~~~~~~~~~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:1734:79 - error TS2344: Type 'WebAudioMedia' does not satisfy the constraint 'IMedia'.
  The types returned by 'create()' are incompatible between these types.
    Type 'WebAudioInstance' is missing the following properties from type 'IMediaInstance<IMedia>': once, on, off

1734 declare class WebAudioInstance extends EventEmitter implements IMediaInstance<WebAudioMedia> {
                                                                                   ~~~~~~~~~~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:1920:5 - error TS2416: Property 'create' in type 'WebAudioMedia' is not assignable to the same property in base type 'IMedia'.
  Type '() => WebAudioInstance' is not assignable to type '() => IMediaInstance<IMedia>'.

1920     create(): WebAudioInstance;
         ~~~~~~

[0m
Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:329:15 - error TS2420: Class 'HTMLAudioInstance' incorrectly implements interface 'IMediaInstance<HTMLAudioMedia>'.
  Type 'HTMLAudioInstance' is missing the following properties from type 'IMediaInstance<HTMLAudioMedia>': once, on, off

329 declare class HTMLAudioInstance extends EventEmitter implements IMediaInstance<HTMLAudioMedia> {
                  ~~~~~~~~~~~~~~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:329:80 - error TS2344: Type 'HTMLAudioMedia' does not satisfy the constraint 'IMedia'.
  The types returned by 'create()' are incompatible between these types.
    Type 'HTMLAudioInstance' is missing the following properties from type 'IMediaInstance<IMedia>': once, on, off

329 declare class HTMLAudioInstance extends EventEmitter implements IMediaInstance<HTMLAudioMedia> {
                                                                                   ~~~~~~~~~~~~~~


Error: node_modules/@pixi/sound/dist/pixi-sound.d.ts:450:5 - error TS2416: Property 'create' in type 'HTMLAudioMedia' is not assignable to the same property in base type 'IMedia'.
  Type '() => HTMLAudioInstance' is not assignable to type '() => IMediaInstance<IMedia>'.

450     create(): HTMLAudioInstance;
        ~~~~~~

**Comment by coojames1010** [comment] 2021-12-31 20:23
This is my tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by bigtimebuddy** [comment] 2021-12-31 21:33
Can you add esModuleInterop to your config? I think that's needed to resolve EventEmitter3 dependency and types.

**Comment by bigtimebuddy** [comment] 2022-01-03 20:08
Did that fix the problem @coojames1010?

**Comment by bigtimebuddy** [comment] 2022-01-06 16:07
I was able to confirm that `esModuleInterop` was the issue here. Used https://github.com/bigtimebuddy/pixi-sound-webpack-example to test. Closing.

**Closed by bigtimebuddy** 2022-01-06 16:07 UTC
